#!/bin/bash
# Base directories and device-specific timestamps
BASE_DIR=~/oasis-data
TIMESTAMP_JETSON="2025-02-28_10-53-19_result_stereo_inertial"
TIMESTAMP_INTEL="2025-02-28_01-04-05_result_stereo_inertial"

# Declare an associative array with path templates (using {scene} as placeholder)
declare -A path_templates
path_templates[jetson_deadlines]="${BASE_DIR}/jetson/${TIMESTAMP_JETSON}_deadlines_{scene}_0_run_1/f_dataset-{scene}_stereo_imu.txt"
path_templates[jetson_normal]="${BASE_DIR}/jetson/${TIMESTAMP_JETSON}_normal_{scene}_0_run_1/f_dataset-{scene}_stereo_imu.txt"
path_templates[jetson_oasis]="${BASE_DIR}/jetson/${TIMESTAMP_JETSON}_oasis_{scene}_0_run_1/f_dataset-{scene}_stereo_imu.txt"
path_templates[intel_deadlines]="${BASE_DIR}/intel/${TIMESTAMP_INTEL}_deadlines_{scene}_0_run_1/f_dataset-{scene}_stereo_imu.txt"
path_templates[intel_normal]="${BASE_DIR}/intel/${TIMESTAMP_INTEL}_normal_{scene}_0_run_1/f_dataset-{scene}_stereo_imu.txt"
path_templates[intel_oasis]="${BASE_DIR}/intel/${TIMESTAMP_INTEL}_oasis_{scene}_0_run_1/f_dataset-{scene}_stereo_imu.txt"

# List of scenes and devices
scenes=("MH01" "MH02" "MH03" "MH04" "MH05")
devices=("jetson" "intel")

for scene in "${scenes[@]}"; do
    gt="Ground_truth/EuRoC_left_cam/${scene}_GT.txt"
    for device in "${devices[@]}"; do
        # Expand templates
        deadlines="${path_templates[${device}_deadlines]//\{scene\}/$scene}"
        normal="${path_templates[${device}_normal]//\{scene\}/$scene}"
        oasis="${path_templates[${device}_oasis]//\{scene\}/$scene}"

        devTitle="$(tr '[:lower:]' '[:upper:]' <<< ${device:0:1})${device:1}"

        # ---------- “all” comparison --------------------------------------
        deadlines_dir=$(dirname "$deadlines")
        oasis_dir=$(dirname "$oasis")
        plot_png="${scene,,}_all_${device}.png"

        python3 evaluate_error_over_time.py --plot "$plot_png" \
               "$gt" "$oasis" "$deadlines" "$normal" --ymax 0.25 \
               --title "${scene} Error Over Time (${devTitle})" \
               --metrics_file "${deadlines_dir}/TrackingTimeStats.txt" \
               --cellManager "${oasis_dir}/cellManager.txt" \
               --cellManager_plot "${scene,,}_${device}_cellManager.png"

        # ---- rename ALL CSVs generated by evaluate_error_over_time -------
        for csv in trajectory_errors_wide.csv fov_mask_*.csv dropped_frames*.csv; do
            [ -f "$csv" ] && mv "$csv" "${device}_${scene}_${csv}"
        done
        # ------------------------------------------------------------------

        # ---------- ATE + scale for each variant --------------------------
        for variant in deadlines normal oasis; do
            echo "${device^^} ${scene} ${variant^^}"
            case $variant in
                deadlines) file_to_use="$deadlines" ;;
                normal)    file_to_use="$normal"    ;;
                oasis)     file_to_use="$oasis"     ;;
            esac

            python3 evaluate_ate_scale.py --verbose "$gt" "$file_to_use"

            # ---- rename CSVs generated by evaluate_ate_scale -------------
            for csv in trajectory_pair.csv ground_truth_traj.csv \
                       estimated_traj_aligned.csv difference_segments.csv; do
                [ -f "$csv" ] && mv "$csv" "${device}_${scene}_${variant}_${csv}"
            done
            # ----------------------------------------------------------------
        done

    done
done

